angular.module('deco', [
  'ngRoute',
  'ngTouch',
  'ngStorage',
  'ngSanitize',
  'ngResource',
  'angular.filter',
  'mobile-angular-ui',
  'djds4rce.angular-socialshare',
  'toaster',
  'ui.ace',
  'pascalprecht.translate',
  'dialogs.main',
  'ui.bootstrap',
  'ui.bootstrap.datetimepicker']);